<div class="entry clr" itemprop="text">

	
	<p>We’ve added a bunch of powerful improvements to make your spreadsheets faster, smarter, and easier to use than ever!</p>
<p>Here’s a quick look at what’s new:</p>
<h2><span class="ez-toc-section" id="Active_Users_Indicator" ez-toc-data-id="#Active_Users_Indicator"></span>Active Users Indicator<span class="ez-toc-section-end"></span></h2>
<p>Now you’ll see an <strong>“Active Users”</strong> indicator right in the toolbar.</p>
<p>It alerts you when multiple users are editing the same sheet, so you can avoid editing conflicts and surprises.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173851/active-users-1.gif" class="oceanwp-lightbox"><img fetchpriority="high" decoding="async" class="aligncenter size-full wp-image-45121" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173851/active-users-1.gif" alt="whats-new-jan-2026" width="1152" height="648"></a></p>
<h2><span class="ez-toc-section" id="Ultra_Performance_Mode" ez-toc-data-id="#Ultra_Performance_Mode"></span>Ultra Performance Mode<span class="ez-toc-section-end"></span></h2>
<p>Say hello to <strong>Ultra Performance Mode</strong> — designed for massive spreadsheets!</p>
<p>It optimizes the sheet to handle very large datasets (40,000+ rows) more efficiently.</p>
<p>You can enable it manually in the <strong>Advanced Options</strong>, and WP Sheet Editor will also auto-enable it when installed on a large site for the very first time.</p>
<h2><span class="ez-toc-section" id="Advanced_Search_Upgrades" ez-toc-data-id="#Advanced_Search_Upgrades"></span>Advanced Search Upgrades<span class="ez-toc-section-end"></span></h2>
<p>We’ve supercharged the Advanced Search tool with several new capabilities to help you find exactly what you need:</p>
<h3><span class="ez-toc-section" id="Find_Duplicate_Values" ez-toc-data-id="#Find_Duplicate_Values"></span>Find Duplicate Values<span class="ez-toc-section-end"></span></h3>
<p>Easily locate posts that have <strong>duplicate values</strong> in any post data or post meta field — perfect for cleaning up duplicates or ensuring unique entries.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21174325/duplicate-terms.gif" class="oceanwp-lightbox"><img decoding="async" class="aligncenter size-full wp-image-45122" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21174325/duplicate-terms.gif" alt="whats-new-jan-2026" width="1152" height="648"></a></p>
<h3><span class="ez-toc-section" id="Find_by_Word_Count" ez-toc-data-id="#Find_by_Word_Count"></span>Find by Word Count<span class="ez-toc-section-end"></span></h3>
<p>Search posts by <strong>word count</strong> in any field — ideal for editors and SEO work.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21153654/word-count.gif" class="oceanwp-lightbox"><img decoding="async" class="aligncenter size-full wp-image-45108" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21153654/word-count.gif" alt="whats-new-jan-2026" width="1400" height="788"></a></p>
<h3><span class="ez-toc-section" id="New_Search_Operators" ez-toc-data-id="#New_Search_Operators"></span>New Search Operators<span class="ez-toc-section-end"></span></h3>
<ul>
<li><strong>not starts with</strong> – find entries that don’t begin with specific text.</li>
<li><strong>not regexp</strong> – use regular expressions to exclude matches with advanced logic.</li>
</ul>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21154211/operators.gif" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45109" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21154211/operators.gif" alt="whats-new-jan-2026" width="1400" height="788"></a></p>
<h3><span class="ez-toc-section" id="Search_by_Children_Count" ez-toc-data-id="#Search_by_Children_Count"></span>Search by Children Count<span class="ez-toc-section-end"></span></h3>
<p>Find posts by the <strong>number of children</strong> (for example, WooCommerce products by variation count, or pages by number of child pages).</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21155628/childposts-variations.gif" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45111" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21155628/childposts-variations.gif" alt="whats-new-jan-2026" width="1400" height="788"></a></p>
<h2><span class="ez-toc-section" id="Columns_Manager_Enhancements" ez-toc-data-id="#Columns_Manager_Enhancements"></span>Columns Manager Enhancements<span class="ez-toc-section-end"></span></h2>
<h3><span class="ez-toc-section" id="Automatically_Disable_Empty_or_Unused_Columns" ez-toc-data-id="#Automatically_Disable_Empty_or_Unused_Columns"></span>Automatically Disable Empty or Unused Columns<span class="ez-toc-section-end"></span></h3>
<p>Keep your spreadsheet clean! You can now automatically <strong>disable all empty</strong> or <strong>unused columns*</strong> with one click. You don’t need to hide columns manually anymore.</p>
<p>*Unused columns requires that you use the sheet a few times, and we consider unused columns the columns that you never edited.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21233725/unused-columns.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45135" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21233725/unused-columns.png" alt="whats-new-jan-2026" width="679" height="387" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21233725/unused-columns.png 679w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21233725/unused-columns-300x171.png 300w" sizes="(max-width: 679px) 100vw, 679px"></a></p>
<h3><span class="ez-toc-section" id="Move_Columns_to_Top_or_Bottom" ez-toc-data-id="#Move_Columns_to_Top_or_Bottom"></span>Move Columns to Top or Bottom<span class="ez-toc-section-end"></span></h3>
<p>Reorganize columns more easily with quick actions to <strong>move any column to the top or bottom</strong> of the list.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45114" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down.png" alt="whats-new-jan-2026" width="1920" height="1080" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down.png 1920w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down-300x169.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down-1024x576.png 1024w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down-768x432.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down-1536x864.png 1536w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21160904/up-and-down-800x450.png 800w" sizes="(max-width: 1920px) 100vw, 1920px"></a></p>
<h3><span class="ez-toc-section" id="New_%E2%80%9CTrue_False%E2%80%9D_Column_Type" ez-toc-data-id="#New_“True_False”_Column_Type"></span>New “True / False” Column Type<span class="ez-toc-section-end"></span></h3>
<p>You can now create columns with a <strong>true/false data type</strong> — perfect for yes/no fields, toggles, or checkbox-style data.</p>
<p>It displays a checkbox that saves true when checked and false when unchecked.</p>
<h3><span class="ez-toc-section" id="Auto-Detection_for_TrueFalse_Fields" ez-toc-data-id="#Auto-Detection_for_TrueFalse_Fields"></span>Auto-Detection for True/False Fields<span class="ez-toc-section-end"></span></h3>
<p><strong>WP Sheet Editor</strong> will now <strong>automatically detect</strong> fields that use true/false values and configure them correctly.</p>
<h2><span class="ez-toc-section" id="Bulk_Editing_Improvements" ez-toc-data-id="#Bulk_Editing_Improvements"></span>Bulk Editing Improvements<span class="ez-toc-section-end"></span></h2>
<h3><span class="ez-toc-section" id="Run_Bulk_Edit_on_Selected_Cells" ez-toc-data-id="#Run_Bulk_Edit_on_Selected_Cells"></span>Run Bulk Edit on Selected Cells<span class="ez-toc-section-end"></span></h3>
<p>Want to change only certain cells instead of entire columns or rows? Now you can run <strong>bulk edits on selected cells</strong> only, giving you ultra-precise control, and allowing you to apply math formulas or bulk edits to the selected cells live.</p>
<p><a href="https://wpsheeteditor.com/wp-content/uploads/2025/10/bulk-edit-cells.gif" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45124" src="https://wpsheeteditor.com/wp-content/uploads/2025/10/bulk-edit-cells.gif" alt="whats-new-jan-2026" width="1152" height="648"></a></p>
<h3><span class="ez-toc-section" id="Shortcut_in_the_WP_Admin_Posts_Screen" ez-toc-data-id="#Shortcut_in_the_WP_Admin_Posts_Screen"></span>Shortcut in the WP Admin Posts Screen<span class="ez-toc-section-end"></span></h3>
<p>We’ve added a shortcut right in the normal <strong>WordPress screen</strong> to open the selected posts directly in WP Sheet Editor for <strong>bulk edit, view, or export.</strong> Faster access to your favorite tool!</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21175413/bulk-actions-wpse.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45128" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21175413/bulk-actions-wpse.png" alt="whats-new-jan-2026" width="946" height="533" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21175413/bulk-actions-wpse.png 946w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21175413/bulk-actions-wpse-300x169.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21175413/bulk-actions-wpse-768x433.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21175413/bulk-actions-wpse-800x450.png 800w" sizes="(max-width: 946px) 100vw, 946px"></a></p>
<h2><span class="ez-toc-section" id="Export_Enhancements" ez-toc-data-id="#Export_Enhancements"></span>Export Enhancements<span class="ez-toc-section-end"></span></h2>
<h3><span class="ez-toc-section" id="Export_Excel_Files" ez-toc-data-id="#Export_Excel_Files"></span>Export Excel Files<span class="ez-toc-section-end"></span></h3>
<p>You can now export your sheet as Excel (.xlsx) files — not just CSV! This makes sharing and collaborating even easier.</p>
<p>Whether you’re sending product data to a client, sharing reports with your team, or doing further analysis in Excel, your exports will be ready to open instantly with all the formatting and column structure preserved.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45117" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel.png" alt="whats-new-jan-2026" width="1920" height="913" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel.png 1920w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel-300x143.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel-1024x487.png 1024w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel-768x365.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172537/excel-1536x730.png 1536w" sizes="(max-width: 1920px) 100vw, 1920px"></a></p>
<h3><span class="ez-toc-section" id="Public_Export_Downloads" ez-toc-data-id="#Public_Export_Downloads"></span>Public Export Downloads<span class="ez-toc-section-end"></span></h3>
<p>Need to share export links with people outside your site?</p>
<p>A new <strong>advanced option</strong> lets you enable <strong>non-logged-in downloads</strong> of your export files safely.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45116" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc.png" alt="whats-new-jan-2026" width="1920" height="817" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc.png 1920w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc-300x128.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc-1024x436.png 1024w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc-768x327.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21172348/publc-1536x654.png 1536w" sizes="(max-width: 1920px) 100vw, 1920px"></a></p>
<h2><span class="ez-toc-section" id="Import_Improvements" ez-toc-data-id="#Import_Improvements"></span>Import Improvements<span class="ez-toc-section-end"></span></h2>
<h3><span class="ez-toc-section" id="Import_Excel_Files" ez-toc-data-id="#Import_Excel_Files"></span>Import Excel Files<span class="ez-toc-section-end"></span></h3>
<p>No more tedious file conversions! WP Sheet Editor now lets you import Excel (.xlsx) files directly. Note, we only read the first worksheet from the Excel file. Just upload your spreadsheet and start updating your WordPress content instantly.</p>
<h3><span class="ez-toc-section" id="Reuse_Previous_Imports" ez-toc-data-id="#Reuse_Previous_Imports"></span>Reuse Previous Imports<span class="ez-toc-section-end"></span></h3>
<p>Do you often import the same kind of data again and again? Now you can rerun any previous import in just a few clicks; no need to go through the entire setup process each time. Note, the saved import will work with any source file as long as the file contains the exact same columns structure. If the file contains a different columns structure, you won’t be able to run the previous import configuration.</p>
<p>WP Sheet Editor remembers your import settings, file mapping, and field configurations, so you can relaunch your recurring imports effortlessly.</p>
<p>This saves tons of time and ensures consistency in every import. Set it once, and reuse it anytime!</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184338/run-previos-imports.gif" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45130" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184338/run-previos-imports.gif" alt="whats-new-jan-2026" width="1152" height="648"></a></p>
<h3><span class="ez-toc-section" id="Dynamic_Columns_During_Import" ez-toc-data-id="#Dynamic_Columns_During_Import"></span>Dynamic Columns During Import<span class="ez-toc-section-end"></span></h3>
<p>You can now add <strong>dynamic columns</strong> to your imports to <strong>create, edit, or customize column values on the fly</strong> as data is being imported.</p>
<p>Have you ever imported a file and noticed that you want to save the title in multiple WordPress fields? or you wanted to remove a symbol from the product prices? or replace a brand or word from the titles? Now you can do it live during the import. You can create new columns with fixed values, concatenate columns, replace values, run math calculations, and run custom PHP functions on your dynamic columns. If you <a href="https://wpsheeteditor.com/extensions/ai/" target="_blank">use our AI addon</a>, you can even run AI prompts on your CSV files live during the import.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173118/dynamic-columns.gif" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45119" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173118/dynamic-columns.gif" alt="whats-new-jan-2026" width="1400" height="666"></a></p>
<h2><span class="ez-toc-section" id="Better_Workspace_Customization" ez-toc-data-id="#Better_Workspace_Customization"></span>Better Workspace Customization<span class="ez-toc-section-end"></span></h2>
<p>You can now dock the <strong>Search</strong>, <strong>Duplicate</strong>, and <strong>Export</strong> modals to the <strong>right side of the screen,</strong>&nbsp;keeping your workspace tidy and efficient while editing.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45120" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search.png" alt="whats-new-jan-2026" width="1920" height="852" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search.png 1920w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search-300x133.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search-1024x454.png 1024w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search-768x341.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21173313/docked-search-1536x682.png 1536w" sizes="(max-width: 1920px) 100vw, 1920px"></a></p>
<h2><span class="ez-toc-section" id="WooCommerce_Product_Shortcuts" ez-toc-data-id="#WooCommerce_Product_Shortcuts"></span>WooCommerce Product Shortcuts<span class="ez-toc-section-end"></span></h2>
<h3><span class="ez-toc-section" id="Display_Variable_Products_with_Variations" ez-toc-data-id="#Display_Variable_Products_with_Variations"></span>Display Variable Products with Variations<span class="ez-toc-section-end"></span></h3>
<p>Quickly display all variable products that already have variations. This helps you check which products are fully configured, review their pricing and stock, or make bulk edits directly from the sheet — no need to browse through each one manually in WooCommerce.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184634/products-with-variations.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45132" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184634/products-with-variations.png" alt="whats-new-jan-2026" width="946" height="533" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184634/products-with-variations.png 946w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184634/products-with-variations-300x169.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184634/products-with-variations-768x433.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184634/products-with-variations-800x450.png 800w" sizes="(max-width: 946px) 100vw, 946px"></a></p>
<h3><span class="ez-toc-section" id="Display_Variable_Products_with_No_Variations" ez-toc-data-id="#Display_Variable_Products_with_No_Variations"></span>Display Variable Products with No Variations<span class="ez-toc-section-end"></span></h3>
<p>Need to find products missing variations? This shortcut instantly shows you variable products that don’t have any variations yet, so you can identify incomplete listings and fix them right away. It’s perfect for store audits, product setup, or team workflows.</p>
<p><a href="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184643/products-without-variations.png" class="oceanwp-lightbox"><img loading="lazy" decoding="async" class="aligncenter size-full wp-image-45133" src="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184643/products-without-variations.png" alt="whats-new-jan-2026" width="946" height="533" srcset="https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184643/products-without-variations.png 946w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184643/products-without-variations-300x169.png 300w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184643/products-without-variations-768x433.png 768w, https://media.wpsheeteditor.com/wp-content/uploads/2025/10/21184643/products-without-variations-800x450.png 800w" sizes="(max-width: 946px) 100vw, 946px"></a></p>
<p>With these shortcuts, you can manage your WooCommerce catalog faster and more confidently, keeping your product data accurate and up to date without leaving WP Sheet Editor.</p>
<p>This update contains hundreds of additional improvements and bug fixes, but the new features above will make your life so much easier.<br>
If you have feature requests, feel free to reach out through our <a href="https://wpsheeteditor.com/company/contact/">contact form</a>.</p>

	
</div>